[platformio]
src_dir = .

; This example demonstrates that the Watchdog library works correctly with
; C++11 and doesn't require C++17 features. We force the gnu++11 standard.
[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++17
build_flags = -std=gnu++11
lib_deps =
    symlink://../..
