[platformio]
src_dir = .

[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags =
    -Werror=unused-result
    -std=gnu++17
    -DUSE_CUSTOM_LOGGER       ; Enable custom Logger for all libraries
    -DWATCHDOG_DEBUG          ; Enable debug logging for Watchdog
    -DCORE_DEBUG_LEVEL=4      ; ESP-IDF debug level
lib_deps =
    symlink://../..
    https://github.com/packerlschupfer/ESP32-Logger.git
