[platformio]
src_dir = .

[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
build_unflags = -std=gnu++11
build_flags = -std=gnu++17
lib_deps =
    symlink://../..

[env:core2_espressif32]
extends = env:esp32dev
platform = espressif32
